# Generated by Django 5.0.3 on 2025-05-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
