# Generated by Django 5.0.3 on 2025-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='disability_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
