# Generated by Django 5.0.3 on 2025-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_applicant_disability_applicant_disability_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=20),
        ),
    ]
