# Generated by Django 5.0.3 on 2025-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0004_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='disability',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
